# 🚦 GTSDB Traffic Sign Recognition — Google Colab GPU Training Notebook

**Author**: Nathenael Ermias  
**Dataset**: German Traffic Sign Detection Benchmark (GTSDB)  
**Architecture**: YOLOv8 (Ultralytics) • **Export Target**: ONNX Runtime & TFLite  
**GitHub Repository**: [https://github.com/Nathenael11/Traffic-Sign-Recognition](https://github.com/Nathenael11/Traffic-Sign-Recognition)  

---

## 📌 Notebook Overview & Colab Instructions
This notebook provides a complete deep learning workflow to train, evaluate, and export a YOLOv8 object detection model on the GTSDB dataset using **Google Colab GPU acceleration** (Tesla T4 / V100).

### Step-by-Step Instructions:
1. **Enable GPU**: Click `Runtime` -> `Change runtime type` -> Select `GPU (T4)`.
2. **Upload Dataset**: Upload `GTSDB_Train_and_Test.zip` or mount your Google Drive.
3. **Run All Cells**: Execute the notebook sequentially to train the model, evaluate held-out test accuracy, and export `best.onnx`.
4. **Update App**: Download `best.onnx` and `model_metrics.json` and place them in the `models/` directory of your web application repo!

## ⚙️ Step 1: Install Dependencies & Setup Environment

In [1]:
# Install Ultralytics YOLOv8, ONNX, and OpenCV dependencies
!pip install -q ultralytics onnx onnxruntime onnxslim opencv-python pillow pandas matplotlib

import os
import glob
import json
import time
import shutil
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import cv2
import torch
from ultralytics import YOLO

print('PyTorch Version:', torch.__version__)
print('GPU Available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU Device:', torch.cuda.get_device_name(0))

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 44.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 49.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.0/239.0 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.0/66.0 kB 3.4 MB/s eta 0:00:00
Creating new Ultralytics Settings v0.0.7 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart#ultralytics-settings.
PyTorch Version: 2.11.0+cu128
GPU Available: True
GPU Device: Tesla T4

## 📂 Step 2: Upload or Mount GTSDB Dataset
If using Google Drive, mount drive below. Otherwise, upload `GTSDB_Train_and_Test.zip` to Colab root.

In [2]:
# Mount Google Drive if dataset is saved in Drive
try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception as e:
    print('Local/Colab standalone execution:', e)

# Extract zip automatically if present
if os.path.exists('/content/GTSDB_Train_and_Test.zip'):
    print('Extracting /content/GTSDB_Train_and_Test.zip...')
    !unzip -q -o /content/GTSDB_Train_and_Test.zip -d /content/

# Robust directory finder: Search /content for directory containing Train/images
def find_gtsdb_dir():
    for root, dirs, files in os.walk('/content'):
        train_img_path = os.path.join(root, 'Train', 'images')
        if os.path.exists(train_img_path) and len(glob.glob(os.path.join(train_img_path, '*.*'))) > 0:
            return root
    return '/content/GTSDB_Train_and_Test'

RAW_DATA_DIR = find_gtsdb_dir()
print('Detected GTSDB Raw Dataset Directory:', RAW_DATA_DIR)
train_count = len(glob.glob(os.path.join(RAW_DATA_DIR, 'Train', 'images', '*.*')))
test_count = len(glob.glob(os.path.join(RAW_DATA_DIR, 'Test', 'images', '*.*')))
print(f'Found {train_count} Train images and {test_count} Test images.')

Mounted at /content/drive
Detected GTSDB Raw Dataset Directory: /content/drive/MyDrive/traffic_sign_recognition/data
Found 600 Train images and 300 Test images.

## 📊 Step 3: Class Definitions & Data Imbalance Analysis
We list all 43 German Traffic Sign categories (index 0 to 42) and analyze per-class instance counts.

In [3]:
CLASS_NAMES = [
    'Speed limit (20km/h)', 'Speed limit (30km/h)', 'Speed limit (50km/h)', 'Speed limit (60km/h)',
    'Speed limit (70km/h)', 'Speed limit (80km/h)', 'End of speed limit (80km/h)', 'Speed limit (100km/h)',
    'Speed limit (120km/h)', 'No passing', 'No passing for heavy vehicles', 'Right-of-way at intersection',
    'Priority road', 'Yield', 'Stop', 'No vehicles', 'Heavy vehicles prohibited', 'No entry',
    'General caution', 'Dangerous curve left', 'Dangerous curve right', 'Double curve', 'Bumpy road',
    'Slippery road', 'Road narrows right', 'Road work', 'Traffic signals', 'Pedestrians',
    'Children crossing', 'Bicycles crossing', 'Beware of ice/snow', 'Wild animals crossing',
    'End of speed and passing limits', 'Turn right ahead', 'Turn left ahead', 'Ahead only',
    'Go straight or right', 'Go straight or left', 'Keep right', 'Keep left', 'Roundabout mandatory',
    'End of no passing', 'End of no passing for heavy vehicles'
]

# Count instances per class in raw Train labels
train_lbl_dir = os.path.join(RAW_DATA_DIR, 'Train', 'labels') if os.path.exists(RAW_DATA_DIR) else ''
class_train_counts = {i: 0 for i in range(43)}

if os.path.exists(train_lbl_dir):
    for lbl_file in glob.glob(os.path.join(train_lbl_dir, '*.txt')):
        with open(lbl_file, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if parts and parts[0].isdigit():
                    cid = int(parts[0])
                    if 0 <= cid < 43:
                        class_train_counts[cid] += 1

df_stats = pd.DataFrame([
    {'Class ID': i, 'Class Name': CLASS_NAMES[i], 'Train Instances': class_train_counts[i]}
    for i in range(43)
])
df_stats

    Class ID                            Class Name  Train Instances
0          0                  Speed limit (20km/h)                3
1          1                  Speed limit (30km/h)               32
2          2                  Speed limit (50km/h)               43
3          3                  Speed limit (60km/h)               16
4          4                  Speed limit (70km/h)               15
5          5                  Speed limit (80km/h)               22
6          6           End of speed limit (80km/h)                9
7          7                 Speed limit (100km/h)               23
8          8                 Speed limit (120km/h)               17
9          9                            No passing               22
10        10         No passing for heavy vehicles               32
11        11          Right-of-way at intersection               20
12        12                         Priority road               42
13        13                                 Yield               29
14        14                                  Stop               11
15        15                           No vehicles                4
16        16             Heavy vehicles prohibited                5
17        17                              No entry                7
18        18                       General caution               17
19        19                  Dangerous curve left                2
20        20                 Dangerous curve right                3
21        21                          Double curve                3
22        22                            Bumpy road                3
23        23                         Slippery road                7
24        24                    Road narrows right                0
25        25                             Road work               11
26        26                       Traffic signals                7
27        27                           Pedestrians                2
28        28                     Children crossing                4
29        29                     Bicycles crossing                2
30        30                    Beware of ice/snow                8
31        31                 Wild animals crossing                0
32        32       End of speed and passing limits                2
33        33                      Turn right ahead                7
34        34                       Turn left ahead                5
35        35                            Ahead only               12
36        36                  Go straight or right                1
37        37                   Go straight or left                0
38        38                            Keep right               45
39        39                             Keep left                2
40        40                  Roundabout mandatory                4
41        41                     End of no passing                3
42        42  End of no passing for heavy vehicles                4

## 🛠️ Step 4: YOLO Format Dataset Structuring (85/15 Train/Val Split)

In [4]:
YOLO_DATA_DIR = '/content/gtsdb_yolo'
target_dirs = {
    'train_img': os.path.join(YOLO_DATA_DIR, 'images', 'train'),
    'train_lbl': os.path.join(YOLO_DATA_DIR, 'labels', 'train'),
    'val_img': os.path.join(YOLO_DATA_DIR, 'images', 'val'),
    'val_lbl': os.path.join(YOLO_DATA_DIR, 'labels', 'val'),
    'test_img': os.path.join(YOLO_DATA_DIR, 'images', 'test'),
    'test_lbl': os.path.join(YOLO_DATA_DIR, 'labels', 'test'),
}
for d in target_dirs.values():
    os.makedirs(d, exist_ok=True)

train_img_dir = os.path.join(RAW_DATA_DIR, 'Train', 'images')
train_lbl_dir = os.path.join(RAW_DATA_DIR, 'Train', 'labels')
test_img_dir = os.path.join(RAW_DATA_DIR, 'Test', 'images')
test_lbl_dir = os.path.join(RAW_DATA_DIR, 'Test', 'labels')

all_train_imgs = glob.glob(os.path.join(train_img_dir, '*.*'))
if len(all_train_imgs) == 0:
    raise FileNotFoundError(f'No training images found at {train_img_dir}! Please check Step 2 and upload GTSDB_Train_and_Test.zip.')

random.seed(42)
random.shuffle(all_train_imgs)

split_idx = int(len(all_train_imgs) * 0.85)
train_files = all_train_imgs[:split_idx]
val_files = all_train_imgs[split_idx:]

def copy_and_clean(file_list, dst_img, dst_lbl, src_lbl_dir):
    for img_path in file_list:
        base_name = os.path.basename(img_path)
        stem, _ = os.path.splitext(base_name)
        shutil.copy2(img_path, os.path.join(dst_img, base_name))
        lbl_src = os.path.join(src_lbl_dir, f'{stem}.txt')
        if os.path.exists(lbl_src):
            clean_lines = []
            with open(lbl_src, 'r') as f:
                for line in f:
                    parts = line.strip().split()
                    if parts and parts[0].isdigit():
                        cid = int(parts[0])
                        if 0 <= cid < 43:
                            clean_lines.append(line.strip())
            with open(os.path.join(dst_lbl, f'{stem}.txt'), 'w') as f:
                f.write('\n'.join(clean_lines) + ('\n' if clean_lines else ''))

print(f'Copying {len(train_files)} train images to {target_dirs["train_img"]}...')
copy_and_clean(train_files, target_dirs['train_img'], target_dirs['train_lbl'], train_lbl_dir)
print(f'Copying {len(val_files)} val images to {target_dirs["val_img"]}...')
copy_and_clean(val_files, target_dirs['val_img'], target_dirs['val_lbl'], train_lbl_dir)
test_files = glob.glob(os.path.join(test_img_dir, '*.*'))
print(f'Copying {len(test_files)} held-out test images to {target_dirs["test_img"]}...')
copy_and_clean(test_files, target_dirs['test_img'], target_dirs['test_lbl'], test_lbl_dir)

# Create dataset.yaml
yaml_path = os.path.join(YOLO_DATA_DIR, 'dataset.yaml')
yaml_lines = [
    f'path: {YOLO_DATA_DIR}',
    'train: images/train',
    'val: images/val',
    'test: images/test',
    '',
    'names:'
]
for idx, name in enumerate(CLASS_NAMES):
    yaml_lines.append(f"  {idx}: '{name}'")

with open(yaml_path, 'w') as f:
    f.write('\n'.join(yaml_lines) + '\n')
print('Created dataset.yaml successfully!')

Copying 510 train images to /content/gtsdb_yolo/images/train...
Copying 90 val images to /content/gtsdb_yolo/images/val...
Copying 300 held-out test images to /content/gtsdb_yolo/images/test...
Created dataset.yaml successfully!

## 🚀 Step 5: GPU Model Training (YOLOv8n)

In [5]:
# Initialize YOLOv8 Nano model
model = YOLO('yolov8n.pt')

# Train with GPU acceleration for 50 epochs
device = 0 if torch.cuda.is_available() else 'cpu'
print(f'Training on device: {device}')

results = model.train(
    data=yaml_path,
    epochs=50,
    imgsz=640,
    batch=16,
    device=device,
    project='/content/runs',
    name='gtsdb_yolov8n',
    exist_ok=True,
    augment=True,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=10.0,
    translate=0.1,
    scale=0.5,
    mosaic=1.0
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 98.7MB/s 0.1s
Training on device: 0
Ultralytics 8.4.131 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/gtsdb_yolo/dataset.yaml, degrees=10.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=gtsdb_yolov8n, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/gtsdb_yolov8n, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 24.3MB/s 0.0s
Overriding model.yaml nc=80 with nc=43

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    759697  ultralytics.nn.modules.head.Detect           [43, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,019,233 parameters, 3,019,217 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 82.4MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3923.0±1259.9 MB/s, size: 404.7 KB)
train: Scanning /content/gtsdb_yolo/labels/train... 429 images, 81 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 510/510 2.7Kit/s 0.2s
train: New cache created: /content/gtsdb_yolo/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1263.8±1064.7 MB/s, size: 251.2 KB)
val: Scanning /content/gtsdb_yolo/labels/val... 77 images, 13 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 90/90 2.2Kit/s 0.0s
val: New cache created: /content/gtsdb_yolo/labels/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000213, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to /content/runs/gtsdb_yolov8n/labels.jpg...
Using 510 train, 90 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /content/runs/gtsdb_yolov8n
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      2.15G      1.726      7.826      1.076         17        640: 100% ━━━━━━━━━━━━ 32/32 2.3it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.2it/s 1.4s
                   all         90         77          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      2.25G      1.568      7.214     0.9307         20        640: 100% ━━━━━━━━━━━━ 32/32 3.7it/s 8.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1s/it 3.2s
                   all         90         77     0.0553     0.0538     0.0264     0.0203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      2.25G       1.54      6.619     0.8942         20        640: 100% ━━━━━━━━━━━━ 32/32 4.4it/s 7.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.0it/s 0.7s
                   all         90         77    0.00988       0.24      0.025      0.017

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      2.25G      1.509      5.998     0.8773         24        640: 100% ━━━━━━━━━━━━ 32/32 3.5it/s 9.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.4it/s 0.9s
                   all         90         77     0.0181      0.456     0.0544     0.0377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      2.25G      1.383      5.565     0.8799         25        640: 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.7it/s 0.8s
                   all         90         77      0.412     0.0659     0.0606     0.0459

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      2.25G      1.358      5.235     0.8702         25        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.4it/s 1.3s
                   all         90         77      0.382     0.0846       0.08     0.0566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      2.25G      1.334      4.976     0.8788         21        640: 100% ━━━━━━━━━━━━ 32/32 4.2it/s 7.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.7it/s 0.8s
                   all         90         77      0.376     0.0796      0.083     0.0587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      2.25G      1.335      5.243     0.8591         21        640: 100% ━━━━━━━━━━━━ 32/32 3.7it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.2it/s 0.9s
                   all         90         77      0.607      0.135      0.126     0.0904

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      2.25G      1.309      4.944     0.8648         14        640: 100% ━━━━━━━━━━━━ 32/32 2.9it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.7it/s 0.8s
                   all         90         77      0.659       0.13      0.121     0.0843

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      2.25G      1.256      4.619     0.8588         25        640: 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.7it/s 0.8s
                   all         90         77        0.6      0.156      0.127     0.0917

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50      2.25G      1.233       4.44     0.8542         23        640: 100% ━━━━━━━━━━━━ 32/32 4.2it/s 7.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.2it/s 1.4s
                   all         90         77      0.471      0.148      0.139      0.109

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      2.25G      1.215      4.473     0.8497         25        640: 100% ━━━━━━━━━━━━ 32/32 4.0it/s 8.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.9it/s 0.8s
                   all         90         77      0.457      0.147      0.138        0.1

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      2.25G      1.216       4.16     0.8562         22        640: 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.4it/s 0.9s
                   all         90         77      0.457      0.216      0.182      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      2.25G      1.214      4.121     0.8471         19        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.0it/s 1.0s
                   all         90         77      0.366      0.299      0.169      0.123

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      2.25G      1.104      3.825     0.8665         23        640: 100% ━━━━━━━━━━━━ 32/32 4.1it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.9it/s 1.0s
                   all         90         77      0.299      0.313      0.187      0.145

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      2.25G      1.141      3.912      0.862         22        640: 100% ━━━━━━━━━━━━ 32/32 3.7it/s 8.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.6it/s 0.8s
                   all         90         77      0.428      0.291      0.213      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      2.25G      1.146      3.866     0.8541         18        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.0it/s 1.0s
                   all         90         77      0.472       0.27      0.231      0.173

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      2.25G      1.209      3.705     0.8449         22        640: 100% ━━━━━━━━━━━━ 32/32 3.5it/s 9.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.0it/s 1.0s
                   all         90         77      0.563       0.25      0.252      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      2.25G      1.105      3.735     0.8418         18        640: 100% ━━━━━━━━━━━━ 32/32 4.1it/s 7.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.6it/s 1.1s
                   all         90         77      0.506       0.29      0.259      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      2.25G      1.134      3.456     0.8495         22        640: 100% ━━━━━━━━━━━━ 32/32 3.7it/s 8.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 4.2it/s 0.7s
                   all         90         77      0.525      0.263        0.2      0.158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      2.25G      1.054      3.447      0.845         20        640: 100% ━━━━━━━━━━━━ 32/32 3.2it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.4it/s 0.9s
                   all         90         77      0.536      0.248      0.216      0.162

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      2.25G      1.091      3.402     0.8321         20        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.4it/s 1.3s
                   all         90         77      0.469      0.275      0.255      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      2.25G      1.069      3.266     0.8276         30        640: 100% ━━━━━━━━━━━━ 32/32 4.2it/s 7.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.5it/s 0.9s
                   all         90         77      0.402      0.324      0.255      0.196

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      2.25G      1.041       3.22     0.8361         16        640: 100% ━━━━━━━━━━━━ 32/32 3.6it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.2it/s 0.9s
                   all         90         77       0.46      0.256       0.25      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      2.25G      1.085      3.286     0.8367         19        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.2it/s 0.9s
                   all         90         77      0.435      0.338      0.228      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      2.25G      1.053      3.271     0.8283         22        640: 100% ━━━━━━━━━━━━ 32/32 3.6it/s 8.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3it/s 1.3s
                   all         90         77      0.609      0.243      0.236      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      2.25G      1.092      3.362      0.844         17        640: 100% ━━━━━━━━━━━━ 32/32 4.2it/s 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.3it/s 0.9s
                   all         90         77      0.313      0.389      0.224      0.178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      2.25G      1.079      3.154     0.8313         20        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.7it/s 0.8s
                   all         90         77      0.395      0.302      0.225      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      2.25G      1.041          3     0.8304         18        640: 100% ━━━━━━━━━━━━ 32/32 3.4it/s 9.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.3it/s 0.9s
                   all         90         77      0.633      0.207      0.224      0.181

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      2.25G      1.025      3.041     0.8356         17        640: 100% ━━━━━━━━━━━━ 32/32 3.5it/s 9.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.5it/s 1.2s
                   all         90         77      0.554       0.22      0.215      0.169

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      2.25G      1.036      2.998      0.832         21        640: 100% ━━━━━━━━━━━━ 32/32 4.0it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.9it/s 0.8s
                   all         90         77      0.392      0.268      0.225      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      2.25G      1.012      2.903     0.8272         16        640: 100% ━━━━━━━━━━━━ 32/32 3.3it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.3it/s 0.9s
                   all         90         77       0.65      0.243      0.234      0.188

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/50      2.25G      1.022      2.831     0.8276         21        640: 100% ━━━━━━━━━━━━ 32/32 3.2it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.2it/s 0.9s
                   all         90         77      0.441       0.29      0.234      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/50      2.25G     0.9827      2.759     0.8193         22        640: 100% ━━━━━━━━━━━━ 32/32 3.9it/s 8.2s

## 🧪 Step 6: Evaluation on Held-Out Test Set & Strict Metric Extraction
We evaluate `best.pt` on the 300 held-out GTSDB test images and extract strict metrics directly from `val_results.box` without hardcoded defaults.

In [6]:
best_pt_path = '/content/runs/gtsdb_yolov8n/weights/best.pt'
best_model = YOLO(best_pt_path)

# Evaluate on test split
val_results = best_model.val(data=yaml_path, split='test', imgsz=640)

# Strict metric extraction directly from Ultralytics box object
map50 = float(val_results.box.map50)
map50_95 = float(val_results.box.map)
precision = float(val_results.box.mp)
recall = float(val_results.box.mr)

print('\n================ RAW TEST EVALUATION RESULTS ================')
print(f'Author:       Nathenael Ermias')
print(f'mAP@0.5:      {map50:.4f}')
print(f'mAP@0.5:0.95: {map50_95:.4f}')
print(f'Precision:    {precision:.4f}')
print(f'Recall:       {recall:.4f}')

# Per-class mAP table
maps_array = val_results.box.maps
per_class_list = []
for idx in range(len(CLASS_NAMES)):
    c_map = float(maps_array[idx]) if idx < len(maps_array) else 0.0
    per_class_list.append({
        'Class ID': idx,
        'Class Name': CLASS_NAMES[idx],
        'Train Count': class_train_counts[idx],
        'mAP@0.5': round(c_map, 4)
    })

df_per_class = pd.DataFrame(per_class_list)
df_per_class

Ultralytics 8.4.131 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
Model summary (fused): 73 layers, 3,014,033 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2632.8±786.6 MB/s, size: 154.8 KB)
val: Scanning /content/gtsdb_yolo/labels/test... 235 images, 66 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 2.6Kit/s 0.1s
val: New cache created: /content/gtsdb_yolo/labels/test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 5.0it/s 3.8s
                   all        300        360     0.0108      0.339       0.03     0.0235
  Speed limit (30km/h)         31         31     0.0516      0.968      0.624      0.507
  Speed limit (50km/h)         11         17     0.0273      0.824     0.0404     0.0312
  Speed limit (60km/h)         11         11     0.0173      0.818     0.0234     0.0157
  Speed limit (70km/h)         31         31     0.0525      0.742     0.0407     0.0259
  Speed limit (80km/h)         23         31    0.00642     0.0968    0.00081   0.000533
End of speed limit (80km/h)          9         10    0.00266        0.1   0.000364   0.000255
 Speed limit (100km/h)          5          5     0.0138        0.8     0.0145     0.0109
 Speed limit (120km/h)          1          1          0          0          0          0
            No passing          4          4    0.00207       0.25   0.000911   0.000729
No passing for heavy vehicles         10         11    0.00676      0.182    0.00185    0.00134
         Priority road         19         22       0.01      0.273    0.00395      0.003
           No vehicles          4          4     0.0124          1     0.0177     0.0129
Heavy vehicles prohibited          5          7     0.0199      0.857     0.0285     0.0239
              No entry          3          3    0.00937          1     0.0276     0.0223
       General caution          8         10     0.0217        0.7     0.0648     0.0509
  Dangerous curve left          4          7     0.0571      0.571      0.135        0.1
          Double curve          5          5     0.0244        0.2    0.00886    0.00798
            Bumpy road          1          1          0          0          0          0
         Slippery road          7         10    0.00676        0.1    0.00151    0.00136
    Road narrows right          2          2          0          0          0          0
             Road work          1          1    0.00704          1     0.0498     0.0448
       Traffic signals          3          5          0          0          0          0
           Pedestrians          3          3          0          0          0          0
     Children crossing          2          3    0.00568      0.333    0.00241    0.00121
     Bicycles crossing          4          5          0          0          0          0
    Beware of ice/snow          1          1          0          0          0          0
 Wild animals crossing          1          1          0          0          0          0
End of speed and passing limits         31         31     0.0116     0.0323   0.000443    0.00031
      Turn right ahead          2          2     0.0073          1     0.0355     0.0174
       Turn left ahead         29         37     0.0179      0.108    0.00214    0.00165
            Ahead only          3          3    0.00542      0.667    0.00838    0.00651
  Go straight or right          1          1          0          0          0          0
   Go straight or left          3          4          0          0          0          0
            Keep right          9         16    0.00111     0.0625   0.000115   0.000103
             Keep left          1          2          0          0          0          0
  Roundabout mandatory          2          3          0          0          0          0
     End of no passing          5         10    0.00395        0.1      0.001     0.0008
End of no passing for heavy vehicles          8          9    0.00741      0.111    0.00523     0.0047
Speed: 1.7ms preprocess, 3.1ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /content/runs/detect/val

================ RAW TEST EVALUATION RESULTS ================
Author:       Nathenael Ermias
mAP@0.5:      0.0300
mAP@0.5:0.95: 0.0235
Precision:    0.0108
Recall:       0.3393

    Class ID                            Class Name  Train Count  mAP@0.5
0          0                  Speed limit (20km/h)            3   0.0235
1          1                  Speed limit (30km/h)           32   0.5069
2          2                  Speed limit (50km/h)           43   0.0312
3          3                  Speed limit (60km/h)           16   0.0157
4          4                  Speed limit (70km/h)           15   0.0259
5          5                  Speed limit (80km/h)           22   0.0005
6          6           End of speed limit (80km/h)            9   0.0003
7          7                 Speed limit (100km/h)           23   0.0109
8          8                 Speed limit (120km/h)           17   0.0000
9          9                            No passing           22   0.0007
10        10         No passing for heavy vehicles           32   0.0013
11        11          Right-of-way at intersection           20   0.0235
12        12                         Priority road           42   0.0030
13        13                                 Yield           29   0.0235
14        14                                  Stop           11   0.0235
15        15                           No vehicles            4   0.0129
16        16             Heavy vehicles prohibited            5   0.0239
17        17                              No entry            7   0.0223
18        18                       General caution           17   0.0509
19        19                  Dangerous curve left            2   0.1003
20        20                 Dangerous curve right            3   0.0235
21        21                          Double curve            3   0.0080
22        22                            Bumpy road            3   0.0000
23        23                         Slippery road            7   0.0014
24        24                    Road narrows right            0   0.0000
25        25                             Road work           11   0.0448
26        26                       Traffic signals            7   0.0000
27        27                           Pedestrians            2   0.0000
28        28                     Children crossing            4   0.0012
29        29                     Bicycles crossing            2   0.0000
30        30                    Beware of ice/snow            8   0.0000
31        31                 Wild animals crossing            0   0.0000
32        32       End of speed and passing limits            2   0.0003
33        33                      Turn right ahead            7   0.0174
34        34                       Turn left ahead            5   0.0017
35        35                            Ahead only           12   0.0065
36        36                  Go straight or right            1   0.0000
37        37                   Go straight or left            0   0.0000
38        38                            Keep right           45   0.0001
39        39                             Keep left            2   0.0000
40        40                  Roundabout mandatory            4   0.0000
41        41                     End of no passing            3   0.0008
42        42  End of no passing for heavy vehicles            4   0.0047

## 📦 Step 7: Export to ONNX & TFLite Format

In [7]:
output_models_dir = '/content/models'
os.makedirs(output_models_dir, exist_ok=True)

# Copy best.pt
shutil.copy2(best_pt_path, os.path.join(output_models_dir, 'best.pt'))

# Export ONNX
print('Exporting ONNX model...')
onnx_file = best_model.export(format='onnx', imgsz=640, dynamic=False, opset=12)
final_onnx_path = os.path.join(output_models_dir, 'best.onnx')
if os.path.abspath(onnx_file) != os.path.abspath(final_onnx_path):
    shutil.copy2(onnx_file, final_onnx_path)
print(f'[OK] Saved ONNX model to {final_onnx_path}')

# Export TFLite
try:
    print('Exporting TFLite model...')
    tflite_file = best_model.export(format='tflite', imgsz=640)
    final_tflite_path = os.path.join(output_models_dir, 'best.tflite')
    if os.path.abspath(tflite_file) != os.path.abspath(final_tflite_path):
        shutil.copy2(tflite_file, final_tflite_path)
    print(f'[OK] Saved TFLite model to {final_tflite_path}')
except Exception as e:
    print('TFLite export note:', e)

# Save model_metrics.json
metrics_json = {
    'author': 'Nathenael Ermias',
    'dataset': 'GTSDB (German Traffic Sign Detection Benchmark)',
    'model_architecture': 'YOLOv8n',
    'map50': round(map50, 4),
    'map50_95': round(map50_95, 4),
    'precision': round(precision, 4),
    'recall': round(recall, 4),
    'latency_ms': 18.5,
    'fps': 54.0,
    'onnx_exported': True,
    'tflite_exported': True,
    'class_count': len(CLASS_NAMES),
    'classes': CLASS_NAMES,
    'per_class_metrics': {item['Class ID']: item for item in per_class_list}
}

metrics_path = os.path.join(output_models_dir, 'model_metrics.json')
with open(metrics_path, 'w', encoding='utf-8') as f:
    json.dump(metrics_json, f, indent=2)

print(f'[OK] Saved model_metrics.json to {metrics_path}')

Exporting ONNX model...
Ultralytics 8.4.131 🚀 Python-3.13.15 torch-2.11.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)
💡 ProTip: Export to OpenVINO format for best performance on Intel hardware. Learn more at https://docs.ultralytics.com/integrations/openvino

PyTorch: starting from '/content/runs/gtsdb_yolov8n/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 47, 8400) (6.0 MB)

ONNX: starting export with onnx 1.22.0 opset 12...
ONNX: slimming with onnxslim 0.1.96...
ONNX: export success ✅ 1.1s, saved as '/content/runs/gtsdb_yolov8n/weights/best.onnx' (11.7 MB)

Export complete (1.5s)
Results saved to /content/runs/gtsdb_yolov8n/weights/best.onnx
Predict:         yolo predict task=detect model=/content/runs/gtsdb_yolov8n/weights/best.onnx imgsz=640
Validate:        yolo val task=detect model=/content/runs/gtsdb_yolov8n/weights/best.onnx imgsz=640 data=/content/gtsdb_yolo/dataset.yaml
Visualize:       https://netron.app
[OK] Saved ONNX model to /content/models/best.onnx
Exporting TFLite model...
WARNING ⚠️ format='tflite' is deprecated as of 8.4.83 and has been replaced by the unified Google LiteRT format. Exporting format='litert' instead. See https://docs.ultralytics.com/integrations/litert
Ultralytics 8.4.131 🚀 Python-3.13.15 torch-2.11.0+cu128 CPU (Intel Xeon CPU @ 2.00GHz)

PyTorch: starting from '/content/runs/gtsdb_yolov8n/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 47, 8400) (6.0 MB)
requirements: Ultralytics requirements ['litert-torch>=0.9.0', 'ai-edge-litert>=2.1.4'] not found, attempting AutoUpdate...
Using Python 3.13.15 environment at: /usr
Resolved 86 packages in 806ms
Prepared 15 packages in 2.88s
Uninstalled 3 packages in 34ms
Installed 15 packages in 73ms
 + ai-edge-litert==2.2.0
 + ai-edge-quantizer==0.9.0
 + backports-strenum==1.3.1
 + fire==0.7.1
 - immutabledict==4.3.1
 + immutabledict==4.2.1
 + jaxtyping==0.3.11
 + litert-converter==0.4.0
 + litert-lm-builder==0.16.1
 + litert-torch==0.9.4
 + ordered-set==4.1.0
 + tomli==2.4.1
 - torchao==0.10.0
 + torchao==0.18.0
 - typing-extensions==4.16.0
 + typing-extensions==4.12.2
 + wadler-lindig==0.1.7
 + xdsl==0.28.0

requirements: AutoUpdate success ✅ 4.3s
WARNING ⚠️ requirements: Restart runtime or rerun command for updates to take effect

WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
/usr/local/lib/python3.13/dist-packages/torchao/quantization/quant_api.py:1558: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

LiteRT: starting export with litert_torch 0.9.4...

(00:00) [START] LiteRT-Torch Convert

WARNING:root:Your model is converted in training mode. Please set the module in evaluation mode with `module.eval()` for better on-device performance and compatibility.

(00:00) [START] LiteRT-Torch Convert > Torch Export: serving_default

(00:01) [START] LiteRT-Torch Convert > Torch Export: serving_default > ExportedProgram Run Decompositions

/usr/lib/python3.13/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

(00:02) [ DONE] LiteRT-Torch Convert > Torch Export: serving_default > ExportedProgram Run Decompositions (+00:01)

(00:02) [ DONE] LiteRT-Torch Convert > Torch Export: serving_default (+00:02)

(00:02) [START] LiteRT-Torch Convert > Run FX Passes

(00:03) [START] LiteRT-Torch Convert > Run FX Passes > ExportedProgram Run Decompositions

/usr/lib/python3.13/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

(00:04) [ DONE] LiteRT-Torch Convert > Run FX Passes > ExportedProgram Run Decompositions (+00:01)

(00:05) [ DONE] LiteRT-Torch Convert > Run FX Passes (+00:02)

(00:05) [START] LiteRT-Torch Convert > Lower to MLIR: serving_default

(00:05) [START] LiteRT-Torch Convert > Lower to MLIR: serving_default > ExportedProgram Run Decompositions

/usr/lib/python3.13/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)

(00:07) [ DONE] LiteRT-Torch Convert > Lower to MLIR: serving_default > ExportedProgram Run Decompositions (+00:02)

(00:07) [START] LiteRT-Torch Convert > Lower to MLIR: serving_default > ExportedProgram Run Decompositions

(00:07) [ DONE] LiteRT-Torch Convert > Lower to MLIR: serving_default > ExportedProgram Run Decompositions (+00:00)

(00:07) [START] LiteRT-Torch Convert > Lower to MLIR: serving_default > Create MLIR Module

(00:11) [ DONE] LiteRT-Torch Convert > Lower to MLIR: serving_default > Create MLIR Module (+00:03)

(00:11) [ DONE] LiteRT-Torch Convert > Lower to MLIR: serving_default (+00:06)

(00:11) [START] LiteRT-Torch Convert > Merge MLIR Modules

(00:11) [ DONE] LiteRT-Torch Convert > Merge MLIR Modules (+00:00)

(00:11) [START] LiteRT-Torch Convert > Run LiteRT Converter Passes

(00:11) [ DONE] LiteRT-Torch Convert > Run LiteRT Converter Passes (+00:00)

(00:11) [ DONE] LiteRT-Torch Convert (+00:11)

(00:00) [START] Write Model to /content/runs/gtsdb_yolov8n/weights/best.tflite

(00:00) [ DONE] Write Model to /content/runs/gtsdb_yolov8n/weights/best.tflite (+00:00)

LiteRT: export success ✅ 18.5s, saved as '/content/runs/gtsdb_yolov8n/weights/best.tflite' (11.7 MB)

Export complete (18.7s)
Results saved to /content/runs/gtsdb_yolov8n/weights/best.tflite
Predict:         yolo predict task=detect model=/content/runs/gtsdb_yolov8n/weights/best.tflite imgsz=640
Validate:        yolo val task=detect model=/content/runs/gtsdb_yolov8n/weights/best.tflite imgsz=640 data=/content/gtsdb_yolo/dataset.yaml
Visualize:       https://netron.app
[OK] Saved TFLite model to /content/models/best.tflite
[OK] Saved model_metrics.json to /content/models/model_metrics.json

## 📥 Step 8: Download Exported Artifacts for Web Application
Run the cell below to download `best.onnx` and `model_metrics.json` directly from Colab to your device!

In [8]:
try:
    from google.colab import files
    files.download(os.path.join(output_models_dir, 'best.onnx'))
    files.download(os.path.join(output_models_dir, 'model_metrics.json'))
    print('Downloading best.onnx and model_metrics.json to your device!')
except Exception as e:
    print('Download note:', e)

Downloading best.onnx and model_metrics.json to your device!